# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tripdar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tripdar
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'
  
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'tripdarTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tripdar-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tripdar-tvOS

  target 'tripdar-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
